# NB: this file was automatically generated by Dynare
#     from AMO_model.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(36, 39);
gp = zeros(36, 36, 39);
end
return (rp, gp)
end
