# NB: this file was automatically generated by Dynare
#     from AMO_model.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(35, 37);
gp = zeros(35, 35, 37);
end
return (rp, gp)
end
