# NB: this file was automatically generated by Dynare
#     from LnR_model.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(46, 47);
gp = zeros(46, 46, 47);
end
return (rp, gp)
end
