// Generated by Julia - Standard Linearization
var L c
    omega_G_1 omega_a_1
    omega_G_2 omega_a_2
    omega_G_3 omega_a_3
    omega_G_4 omega_a_4
    omega_G_5 omega_a_5
    omega_G_6 omega_a_6
    omega_G_7 omega_a_7
    L_k1 alpha_k1 omega_a_group_1
    L_k2 alpha_k2 omega_a_group_2
    L_k3 alpha_k3 omega_a_group_3
    b_1 R_1_1 alpha_ik_1
    b_2 R_1_2 alpha_ik_2
    b_3 R_1_3 alpha_ik_3
    b_4 R_2_1 alpha_ik_4
    b_5 R_2_2 alpha_ik_5
    b_6 R_3_1 alpha_ik_6
    b_7 R_3_2 alpha_ik_7
;

varexo
    eps_G_1 eps_a_1
    eps_G_2 eps_a_2
    eps_G_3 eps_a_3
    eps_G_4 eps_a_4
    eps_G_5 eps_a_5
    eps_G_6 eps_a_6
    eps_G_7 eps_a_7
    eps_a_group_1
    eps_a_group_2
    eps_a_group_3
;

parameters
    sigma
    psi
    y
    rho_G
    rho_a
    gamma
    sig_a
    eta
    sig_G
    beta
    rho_k1 alpha_bar_k1 delta_k1
    rho_k2 alpha_bar_k2 delta_k2
    rho_k3 alpha_bar_k3 delta_k3
    alpha_bar_ik_1 delta_ik_1 b_bar_1 phi_1
    alpha_bar_ik_2 delta_ik_2 b_bar_2 phi_2
    alpha_bar_ik_3 delta_ik_3 b_bar_3 phi_3
    alpha_bar_ik_4 delta_ik_4 b_bar_4 phi_4
    alpha_bar_ik_5 delta_ik_5 b_bar_5 phi_5
    alpha_bar_ik_6 delta_ik_6 b_bar_6 phi_6
    alpha_bar_ik_7 delta_ik_7 b_bar_7 phi_7
;

// --- CALIBRATION ---
sigma = 2.0;
psi = 0.5;
y = 1.0;
rho_G = 0.9;
rho_a = 0.9;
gamma = 2.0;
sig_a = 0.01;
eta = 1.5;
sig_G = 0.01;
beta = 0.99;

rho_k1 = 10.0; alpha_bar_k1 = 0.5; delta_k1 = 0.2;
rho_k2 = 2.0; alpha_bar_k2 = 0.2142857142857143; delta_k2 = 0.8;
rho_k3 = 4.0; alpha_bar_k3 = 0.28571428571428575; delta_k3 = 0.5;

alpha_bar_ik_1 = 0.2564102564102564; delta_ik_1 = 0.2;
b_bar_1 = 2.0; phi_1 = 0.1;
alpha_bar_ik_2 = 0.30769230769230765; delta_ik_2 = 0.3;
b_bar_2 = 2.0; phi_2 = 0.3;
alpha_bar_ik_3 = 0.43589743589743585; delta_ik_3 = 0.1;
b_bar_3 = 2.0; phi_3 = 0.2;
alpha_bar_ik_4 = 0.6; delta_ik_4 = 0.9;
b_bar_4 = 0.5; phi_4 = 1.0;
alpha_bar_ik_5 = 0.4; delta_ik_5 = 0.9;
b_bar_5 = 0.5; phi_5 = 1.5;
alpha_bar_ik_6 = 0.23809523809523808; delta_ik_6 = 0.6;
b_bar_6 = 1.0; phi_6 = 0.7;
alpha_bar_ik_7 = 0.7619047619047619; delta_ik_7 = 0.4;
b_bar_7 = 1.0; phi_7 = 0.5;

model;
    c = y;

    omega_G_1 = rho_G * omega_G_1(-1) + sig_G * eps_G_1;
    omega_a_1 = rho_a * omega_a_1(-1) + sig_a * eps_a_1;
    omega_G_2 = rho_G * omega_G_2(-1) + sig_G * eps_G_2;
    omega_a_2 = rho_a * omega_a_2(-1) + sig_a * eps_a_2;
    omega_G_3 = rho_G * omega_G_3(-1) + sig_G * eps_G_3;
    omega_a_3 = rho_a * omega_a_3(-1) + sig_a * eps_a_3;
    omega_G_4 = rho_G * omega_G_4(-1) + sig_G * eps_G_4;
    omega_a_4 = rho_a * omega_a_4(-1) + sig_a * eps_a_4;
    omega_G_5 = rho_G * omega_G_5(-1) + sig_G * eps_G_5;
    omega_a_5 = rho_a * omega_a_5(-1) + sig_a * eps_a_5;
    omega_G_6 = rho_G * omega_G_6(-1) + sig_G * eps_G_6;
    omega_a_6 = rho_a * omega_a_6(-1) + sig_a * eps_a_6;
    omega_G_7 = rho_G * omega_G_7(-1) + sig_G * eps_G_7;
    omega_a_7 = rho_a * omega_a_7(-1) + sig_a * eps_a_7;
    omega_a_group_1 = rho_a * omega_a_group_1(-1) + sig_a * eps_a_group_1;
    omega_a_group_2 = rho_a * omega_a_group_2(-1) + sig_a * eps_a_group_2;
    omega_a_group_3 = rho_a * omega_a_group_3(-1) + sig_a * eps_a_group_3;

    L = ( (alpha_k1 * L_k1^((eta-1)/eta)) + (alpha_k2 * L_k2^((eta-1)/eta)) + (alpha_k3 * L_k3^((eta-1)/eta)) )^(eta/(eta-1));
    L_k1 = ( (alpha_ik_1 * b_1^((rho_k1-1)/rho_k1)) + (alpha_ik_2 * b_2^((rho_k1-1)/rho_k1)) + (alpha_ik_3 * b_3^((rho_k1-1)/rho_k1)) )^(rho_k1/(rho_k1-1));
    L_k2 = ( (alpha_ik_4 * b_4^((rho_k2-1)/rho_k2)) + (alpha_ik_5 * b_5^((rho_k2-1)/rho_k2)) )^(rho_k2/(rho_k2-1));
    L_k3 = ( (alpha_ik_6 * b_6^((rho_k3-1)/rho_k3)) + (alpha_ik_7 * b_7^((rho_k3-1)/rho_k3)) )^(rho_k3/(rho_k3-1));
    alpha_k1 = (alpha_bar_k1 * exp(delta_k1 * omega_a_group_1)) / ( (alpha_bar_k1 * exp(delta_k1 * omega_a_group_1)) + (alpha_bar_k2 * exp(delta_k2 * omega_a_group_2)) + (alpha_bar_k3 * exp(delta_k3 * omega_a_group_3)) );
    alpha_k2 = (alpha_bar_k2 * exp(delta_k2 * omega_a_group_2)) / ( (alpha_bar_k1 * exp(delta_k1 * omega_a_group_1)) + (alpha_bar_k2 * exp(delta_k2 * omega_a_group_2)) + (alpha_bar_k3 * exp(delta_k3 * omega_a_group_3)) );
    alpha_k3 = (alpha_bar_k3 * exp(delta_k3 * omega_a_group_3)) / ( (alpha_bar_k1 * exp(delta_k1 * omega_a_group_1)) + (alpha_bar_k2 * exp(delta_k2 * omega_a_group_2)) + (alpha_bar_k3 * exp(delta_k3 * omega_a_group_3)) );
    alpha_ik_1 = (alpha_bar_ik_1 * exp(delta_ik_1 * omega_a_1)) / ( (alpha_bar_ik_1 * exp(delta_ik_1 * omega_a_1)) + (alpha_bar_ik_2 * exp(delta_ik_2 * omega_a_2)) + (alpha_bar_ik_3 * exp(delta_ik_3 * omega_a_3)) );
    alpha_ik_2 = (alpha_bar_ik_2 * exp(delta_ik_2 * omega_a_2)) / ( (alpha_bar_ik_1 * exp(delta_ik_1 * omega_a_1)) + (alpha_bar_ik_2 * exp(delta_ik_2 * omega_a_2)) + (alpha_bar_ik_3 * exp(delta_ik_3 * omega_a_3)) );
    alpha_ik_3 = (alpha_bar_ik_3 * exp(delta_ik_3 * omega_a_3)) / ( (alpha_bar_ik_1 * exp(delta_ik_1 * omega_a_1)) + (alpha_bar_ik_2 * exp(delta_ik_2 * omega_a_2)) + (alpha_bar_ik_3 * exp(delta_ik_3 * omega_a_3)) );
    alpha_ik_4 = (alpha_bar_ik_4 * exp(delta_ik_4 * omega_a_4)) / ( (alpha_bar_ik_4 * exp(delta_ik_4 * omega_a_4)) + (alpha_bar_ik_5 * exp(delta_ik_5 * omega_a_5)) );
    alpha_ik_5 = (alpha_bar_ik_5 * exp(delta_ik_5 * omega_a_5)) / ( (alpha_bar_ik_4 * exp(delta_ik_4 * omega_a_4)) + (alpha_bar_ik_5 * exp(delta_ik_5 * omega_a_5)) );
    alpha_ik_6 = (alpha_bar_ik_6 * exp(delta_ik_6 * omega_a_6)) / ( (alpha_bar_ik_6 * exp(delta_ik_6 * omega_a_6)) + (alpha_bar_ik_7 * exp(delta_ik_7 * omega_a_7)) );
    alpha_ik_7 = (alpha_bar_ik_7 * exp(delta_ik_7 * omega_a_7)) / ( (alpha_bar_ik_6 * exp(delta_ik_6 * omega_a_6)) + (alpha_bar_ik_7 * exp(delta_ik_7 * omega_a_7)) );

    b_1 = b_bar_1 + phi_1 * omega_G_1;
    1 - beta * R_1_1 = (psi / c^sigma) * alpha_k1 * alpha_ik_1 * L^(1/eta - gamma) * L_k1^(1/rho_k1 - 1/eta) * b_1^(-1/rho_k1);
    b_2 = b_bar_2 + phi_2 * omega_G_2;
    1 - beta * R_1_2 = (psi / c^sigma) * alpha_k1 * alpha_ik_2 * L^(1/eta - gamma) * L_k1^(1/rho_k1 - 1/eta) * b_2^(-1/rho_k1);
    b_3 = b_bar_3 + phi_3 * omega_G_3;
    1 - beta * R_1_3 = (psi / c^sigma) * alpha_k1 * alpha_ik_3 * L^(1/eta - gamma) * L_k1^(1/rho_k1 - 1/eta) * b_3^(-1/rho_k1);
    b_4 = b_bar_4 + phi_4 * omega_G_4;
    1 - beta * R_2_1 = (psi / c^sigma) * alpha_k2 * alpha_ik_4 * L^(1/eta - gamma) * L_k2^(1/rho_k2 - 1/eta) * b_4^(-1/rho_k2);
    b_5 = b_bar_5 + phi_5 * omega_G_5;
    1 - beta * R_2_2 = (psi / c^sigma) * alpha_k2 * alpha_ik_5 * L^(1/eta - gamma) * L_k2^(1/rho_k2 - 1/eta) * b_5^(-1/rho_k2);
    b_6 = b_bar_6 + phi_6 * omega_G_6;
    1 - beta * R_3_1 = (psi / c^sigma) * alpha_k3 * alpha_ik_6 * L^(1/eta - gamma) * L_k3^(1/rho_k3 - 1/eta) * b_6^(-1/rho_k3);
    b_7 = b_bar_7 + phi_7 * omega_G_7;
    1 - beta * R_3_2 = (psi / c^sigma) * alpha_k3 * alpha_ik_7 * L^(1/eta - gamma) * L_k3^(1/rho_k3 - 1/eta) * b_7^(-1/rho_k3);
end;

initval;
    c = y; L = 1.0;
    omega_G_1 = 0; omega_a_1 = 0;
    omega_G_2 = 0; omega_a_2 = 0;
    omega_G_3 = 0; omega_a_3 = 0;
    omega_G_4 = 0; omega_a_4 = 0;
    omega_G_5 = 0; omega_a_5 = 0;
    omega_G_6 = 0; omega_a_6 = 0;
    omega_G_7 = 0; omega_a_7 = 0;
    omega_a_group_1 = 0;
    omega_a_group_2 = 0;
    omega_a_group_3 = 0;
    L_k1 = 1.0; alpha_k1 = 0.5;
    L_k2 = 1.0; alpha_k2 = 0.2142857142857143;
    L_k3 = 1.0; alpha_k3 = 0.28571428571428575;
    b_1 = 2.0;
    alpha_ik_1 = 0.2564102564102564;
    R_1_1 = 0.9496870634850553;
    b_2 = 2.0;
    alpha_ik_2 = 0.30769230769230765;
    R_1_2 = 0.9376042741618642;
    b_3 = 2.0;
    alpha_ik_3 = 0.43589743589743585;
    R_1_3 = 0.9073973008538868;
    b_4 = 0.5;
    alpha_ik_4 = 0.6;
    R_2_1 = 0.9182689605962637;
    b_5 = 0.5;
    alpha_ik_5 = 0.4;
    R_2_2 = 0.9488796437645124;
    b_6 = 1.0;
    alpha_ik_6 = 0.23809523809523808;
    R_3_1 = 0.97574383288669;
    b_7 = 1.0;
    alpha_ik_7 = 0.7619047619047619;
    R_3_2 = 0.9001580430151859;
end;

shocks;
    var eps_G_1 = 1; var eps_a_1 = 1;
    var eps_G_2 = 1; var eps_a_2 = 1;
    var eps_G_3 = 1; var eps_a_3 = 1;
    var eps_G_4 = 1; var eps_a_4 = 1;
    var eps_G_5 = 1; var eps_a_5 = 1;
    var eps_G_6 = 1; var eps_a_6 = 1;
    var eps_G_7 = 1; var eps_a_7 = 1;
    var eps_a_group_1 = 1;
    var eps_a_group_2 = 1;
    var eps_a_group_3 = 1;
end;

steady;
check;
stoch_simul(order=1, irf=20, graph_format=pdf);
