// ============================================================================
// Overlapping Liquidity Baskets Model (AMO)
// Generated automatically by gen_model.jl
// DO NOT EDIT THIS FILE DIRECTLY - Modify gen_model.jl instead
// ============================================================================

// --- ENDOGENOUS VARIABLES ---
var
    L                      // Aggregate liquidity index
    c                      // Consumption
    omega_G_1             // Supply shock for asset 1
    omega_a_1             // Asset-specific preference shock 1
    omega_G_2             // Supply shock for asset 2
    omega_a_2             // Asset-specific preference shock 2
    omega_G_3             // Supply shock for asset 3
    omega_a_3             // Asset-specific preference shock 3
    omega_G_4             // Supply shock for asset 4
    omega_a_4             // Asset-specific preference shock 4
    omega_G_5             // Supply shock for asset 5
    omega_a_5             // Asset-specific preference shock 5
    L_k1                  // Liquidity index for basket 1
    alpha_k1              // Time-varying weight on basket 1
    omega_a_basket_1      // Basket-level preference shock 1
    L_k2                  // Liquidity index for basket 2
    alpha_k2              // Time-varying weight on basket 2
    omega_a_basket_2      // Basket-level preference shock 2

    // Asset Returns (Gross)
    R_1                   // Gross return on asset 1
    R_2                   // Gross return on asset 2
    R_3                   // Gross return on asset 3
    R_4                   // Gross return on asset 4
    R_5                   // Gross return on asset 5

    // Asset Holdings by Basket: b_i_k = holdings of asset i in basket k
    b_1_k1           // Asset 1 in basket 1
    alpha_1_k1       // Weight on asset 1 in basket 1
    b_2_k1           // Asset 2 in basket 1
    alpha_2_k1       // Weight on asset 2 in basket 1
    b_3_k1           // Asset 3 in basket 1
    alpha_3_k1       // Weight on asset 3 in basket 1
    b_3_k2           // Asset 3 in basket 2
    alpha_3_k2       // Weight on asset 3 in basket 2
    b_4_k2           // Asset 4 in basket 2
    alpha_4_k2       // Weight on asset 4 in basket 2
    b_5_k2           // Asset 5 in basket 2
    alpha_5_k2       // Weight on asset 5 in basket 2
;

// --- EXOGENOUS SHOCKS (Innovations) ---
varexo
    eps_G_1               // Supply shock innovation, asset 1
    eps_a_1               // Preference shock innovation, asset 1
    eps_G_2               // Supply shock innovation, asset 2
    eps_a_2               // Preference shock innovation, asset 2
    eps_G_3               // Supply shock innovation, asset 3
    eps_a_3               // Preference shock innovation, asset 3
    eps_G_4               // Supply shock innovation, asset 4
    eps_a_4               // Preference shock innovation, asset 4
    eps_G_5               // Supply shock innovation, asset 5
    eps_a_5               // Preference shock innovation, asset 5
    eps_a_basket_1        // Basket preference shock innovation 1
    eps_a_basket_2        // Basket preference shock innovation 2
;

// --- PARAMETERS ---
parameters
    // Global preferences and shocks
    sigma
    psi
    y
    rho_G
    rho_a
    gamma
    sig_a
    eta
    sig_G
    beta

    // Basket-level parameters
    rho_k1                // Intra-basket substitution elasticity
    alpha_bar_k1          // Steady-state basket weight
    delta_k1              // Basket shock sensitivity
    rho_k2                // Intra-basket substitution elasticity
    alpha_bar_k2          // Steady-state basket weight
    delta_k2              // Basket shock sensitivity

    // Asset-level parameters
    b_bar_1               // Steady-state supply
    phi_1                 // Supply elasticity
    delta_idio_1          // Idiosyncratic shock sensitivity
    b_bar_2               // Steady-state supply
    phi_2                 // Supply elasticity
    delta_idio_2          // Idiosyncratic shock sensitivity
    b_bar_3               // Steady-state supply
    phi_3                 // Supply elasticity
    delta_idio_3          // Idiosyncratic shock sensitivity
    b_bar_4               // Steady-state supply
    phi_4                 // Supply elasticity
    delta_idio_4          // Idiosyncratic shock sensitivity
    b_bar_5               // Steady-state supply
    phi_5                 // Supply elasticity
    delta_idio_5          // Idiosyncratic shock sensitivity

    // Intra-basket asset weights
    alpha_bar_1_k1   // SS weight: asset 1 in basket 1
    alpha_bar_2_k1   // SS weight: asset 2 in basket 1
    alpha_bar_3_k1   // SS weight: asset 3 in basket 1
    alpha_bar_3_k2   // SS weight: asset 3 in basket 2
    alpha_bar_4_k2   // SS weight: asset 4 in basket 2
    alpha_bar_5_k2   // SS weight: asset 5 in basket 2
;

// ============================================================================
// CALIBRATION: Parameter Values
// ============================================================================

// Global Parameters
sigma = 2.0;
psi = 0.5;
y = 1.0;
rho_G = 0.9;
rho_a = 0.9;
gamma = 2.0;
sig_a = 0.01;
eta = 1.5;
sig_G = 0.01;
beta = 0.99;

// Basket Parameters
rho_k1 = 10.0;           // Basket 1 substitution elasticity
alpha_bar_k1 = 0.5;     // Basket 1 steady-state weight
delta_k1 = 0.2;         // Basket 1 shock sensitivity
rho_k2 = 2.0;           // Basket 2 substitution elasticity
alpha_bar_k2 = 0.5;     // Basket 2 steady-state weight
delta_k2 = 0.8;         // Basket 2 shock sensitivity

// Asset Parameters
b_bar_1 = 2.0;          // Asset 1 supply
phi_1 = 0.1;              // Asset 1 supply elasticity
delta_idio_1 = 0.1;      // Asset 1 shock sensitivity
b_bar_2 = 2.0;          // Asset 2 supply
phi_2 = 0.1;              // Asset 2 supply elasticity
delta_idio_2 = 0.1;      // Asset 2 shock sensitivity
b_bar_3 = 1.0;          // Asset 3 supply
phi_3 = 0.2;              // Asset 3 supply elasticity
delta_idio_3 = 0.5;      // Asset 3 shock sensitivity
b_bar_4 = 0.5;          // Asset 4 supply
phi_4 = 1.5;              // Asset 4 supply elasticity
delta_idio_4 = 0.9;      // Asset 4 shock sensitivity
b_bar_5 = 0.5;          // Asset 5 supply
phi_5 = 1.5;              // Asset 5 supply elasticity
delta_idio_5 = 0.9;      // Asset 5 shock sensitivity

// Intra-Basket Asset Weights (Equal within basket)
alpha_bar_1_k1 = 0.3333333333333333;    // Asset 1 in basket 1
alpha_bar_2_k1 = 0.3333333333333333;    // Asset 2 in basket 1
alpha_bar_3_k1 = 0.3333333333333333;    // Asset 3 in basket 1
alpha_bar_3_k2 = 0.3333333333333333;    // Asset 3 in basket 2
alpha_bar_4_k2 = 0.3333333333333333;    // Asset 4 in basket 2
alpha_bar_5_k2 = 0.3333333333333333;    // Asset 5 in basket 2

model;
    c = y;

    omega_G_1 = rho_G * omega_G_1(-1) + sig_G * eps_G_1;
    omega_a_1 = rho_a * omega_a_1(-1) + sig_a * eps_a_1;
    omega_G_2 = rho_G * omega_G_2(-1) + sig_G * eps_G_2;
    omega_a_2 = rho_a * omega_a_2(-1) + sig_a * eps_a_2;
    omega_G_3 = rho_G * omega_G_3(-1) + sig_G * eps_G_3;
    omega_a_3 = rho_a * omega_a_3(-1) + sig_a * eps_a_3;
    omega_G_4 = rho_G * omega_G_4(-1) + sig_G * eps_G_4;
    omega_a_4 = rho_a * omega_a_4(-1) + sig_a * eps_a_4;
    omega_G_5 = rho_G * omega_G_5(-1) + sig_G * eps_G_5;
    omega_a_5 = rho_a * omega_a_5(-1) + sig_a * eps_a_5;
    omega_a_basket_1 = rho_a * omega_a_basket_1(-1) + sig_a * eps_a_basket_1;
    omega_a_basket_2 = rho_a * omega_a_basket_2(-1) + sig_a * eps_a_basket_2;

    L = ( (alpha_k1 * L_k1^((eta-1)/eta)) + (alpha_k2 * L_k2^((eta-1)/eta)) )^(eta/(eta-1));

    L_k1 = ( (alpha_1_k1 * b_1_k1^((rho_k1-1)/rho_k1)) + (alpha_2_k1 * b_2_k1^((rho_k1-1)/rho_k1)) + (alpha_3_k1 * b_3_k1^((rho_k1-1)/rho_k1)) )^(rho_k1/(rho_k1-1));
    L_k2 = ( (alpha_3_k2 * b_3_k2^((rho_k2-1)/rho_k2)) + (alpha_4_k2 * b_4_k2^((rho_k2-1)/rho_k2)) + (alpha_5_k2 * b_5_k2^((rho_k2-1)/rho_k2)) )^(rho_k2/(rho_k2-1));

    alpha_k1 = (alpha_bar_k1 * exp(delta_k1 * omega_a_basket_1)) / ((alpha_bar_k1 * exp(delta_k1 * omega_a_basket_1)) + (alpha_bar_k2 * exp(delta_k2 * omega_a_basket_2)));
    alpha_k2 = (alpha_bar_k2 * exp(delta_k2 * omega_a_basket_2)) / ((alpha_bar_k1 * exp(delta_k1 * omega_a_basket_1)) + (alpha_bar_k2 * exp(delta_k2 * omega_a_basket_2)));
    alpha_1_k1 = (alpha_bar_1_k1 * exp(delta_idio_1 * omega_a_1)) / ((alpha_bar_1_k1 * exp(delta_idio_1 * omega_a_1)) + (alpha_bar_2_k1 * exp(delta_idio_2 * omega_a_2)) + (alpha_bar_3_k1 * exp(delta_idio_3 * omega_a_3)));
    alpha_2_k1 = (alpha_bar_2_k1 * exp(delta_idio_2 * omega_a_2)) / ((alpha_bar_1_k1 * exp(delta_idio_1 * omega_a_1)) + (alpha_bar_2_k1 * exp(delta_idio_2 * omega_a_2)) + (alpha_bar_3_k1 * exp(delta_idio_3 * omega_a_3)));
    alpha_3_k1 = (alpha_bar_3_k1 * exp(delta_idio_3 * omega_a_3)) / ((alpha_bar_1_k1 * exp(delta_idio_1 * omega_a_1)) + (alpha_bar_2_k1 * exp(delta_idio_2 * omega_a_2)) + (alpha_bar_3_k1 * exp(delta_idio_3 * omega_a_3)));
    alpha_3_k2 = (alpha_bar_3_k2 * exp(delta_idio_3 * omega_a_3)) / ((alpha_bar_3_k2 * exp(delta_idio_3 * omega_a_3)) + (alpha_bar_4_k2 * exp(delta_idio_4 * omega_a_4)) + (alpha_bar_5_k2 * exp(delta_idio_5 * omega_a_5)));
    alpha_4_k2 = (alpha_bar_4_k2 * exp(delta_idio_4 * omega_a_4)) / ((alpha_bar_3_k2 * exp(delta_idio_3 * omega_a_3)) + (alpha_bar_4_k2 * exp(delta_idio_4 * omega_a_4)) + (alpha_bar_5_k2 * exp(delta_idio_5 * omega_a_5)));
    alpha_5_k2 = (alpha_bar_5_k2 * exp(delta_idio_5 * omega_a_5)) / ((alpha_bar_3_k2 * exp(delta_idio_3 * omega_a_3)) + (alpha_bar_4_k2 * exp(delta_idio_4 * omega_a_4)) + (alpha_bar_5_k2 * exp(delta_idio_5 * omega_a_5)));

    b_bar_1 + phi_1 * omega_G_1 = b_1_k1;
    b_bar_2 + phi_2 * omega_G_2 = b_2_k1;
    b_bar_3 + phi_3 * omega_G_3 = b_3_k1 + b_3_k2;
    b_bar_4 + phi_4 * omega_G_4 = b_4_k2;
    b_bar_5 + phi_5 * omega_G_5 = b_5_k2;

    1 - beta * R_1 = (psi / c^(-sigma)) * alpha_k1 * alpha_1_k1 * L^(1/eta - gamma) * L_k1^(1/rho_k1 - 1/eta) * b_1_k1^(-1/rho_k1);
    1 - beta * R_2 = (psi / c^(-sigma)) * alpha_k1 * alpha_2_k1 * L^(1/eta - gamma) * L_k1^(1/rho_k1 - 1/eta) * b_2_k1^(-1/rho_k1);
    1 - beta * R_3 = (psi / c^(-sigma)) * alpha_k1 * alpha_3_k1 * L^(1/eta - gamma) * L_k1^(1/rho_k1 - 1/eta) * b_3_k1^(-1/rho_k1);
    1 - beta * R_3 = (psi / c^(-sigma)) * alpha_k2 * alpha_3_k2 * L^(1/eta - gamma) * L_k2^(1/rho_k2 - 1/eta) * b_3_k2^(-1/rho_k2);
    1 - beta * R_4 = (psi / c^(-sigma)) * alpha_k2 * alpha_4_k2 * L^(1/eta - gamma) * L_k2^(1/rho_k2 - 1/eta) * b_4_k2^(-1/rho_k2);
    1 - beta * R_5 = (psi / c^(-sigma)) * alpha_k2 * alpha_5_k2 * L^(1/eta - gamma) * L_k2^(1/rho_k2 - 1/eta) * b_5_k2^(-1/rho_k2);
end;

// ============================================================================
// INITIAL/STEADY STATE VALUES
// ============================================================================

initval;
    // Consumption and aggregate liquidity
    c = y;
    L = 1.0;

    // Shocks initialized at zero (steady state)
    omega_G_1 = 0;
    omega_a_1 = 0;
    omega_G_2 = 0;
    omega_a_2 = 0;
    omega_G_3 = 0;
    omega_a_3 = 0;
    omega_G_4 = 0;
    omega_a_4 = 0;
    omega_G_5 = 0;
    omega_a_5 = 0;
    omega_a_basket_1 = 0;
    omega_a_basket_2 = 0;

    // Asset returns and allocations
    R_1 = 1.0/beta - 0.005;  // Slight premium over risk-free rate
    b_1_k1 = 2.0;
    alpha_1_k1 = 0.3333333333333333;
    R_2 = 1.0/beta - 0.005;  // Slight premium over risk-free rate
    b_2_k1 = 2.0;
    alpha_2_k1 = 0.3333333333333333;
    R_3 = 1.0/beta - 0.005;  // Slight premium over risk-free rate
    b_3_k1 = 0.5;
    alpha_3_k1 = 0.3333333333333333;
    b_3_k2 = 0.5;
    alpha_3_k2 = 0.3333333333333333;
    R_4 = 1.0/beta - 0.005;  // Slight premium over risk-free rate
    b_4_k2 = 0.5;
    alpha_4_k2 = 0.3333333333333333;
    R_5 = 1.0/beta - 0.005;  // Slight premium over risk-free rate
    b_5_k2 = 0.5;
    alpha_5_k2 = 0.3333333333333333;

    // Basket aggregates
    L_k1 = 1.0;
    alpha_k1 = 0.5;
    L_k2 = 1.0;
    alpha_k2 = 0.5;
end;

// ============================================================================
// SHOCK VARIANCES
// ============================================================================

shocks;
    var eps_G_1 = 1;          // Supply shock variance
    var eps_a_1 = 1;          // Preference shock variance
    var eps_G_2 = 1;          // Supply shock variance
    var eps_a_2 = 1;          // Preference shock variance
    var eps_G_3 = 1;          // Supply shock variance
    var eps_a_3 = 1;          // Preference shock variance
    var eps_G_4 = 1;          // Supply shock variance
    var eps_a_4 = 1;          // Preference shock variance
    var eps_G_5 = 1;          // Supply shock variance
    var eps_a_5 = 1;          // Preference shock variance
    var eps_a_basket_1 = 1;   // Basket shock variance
    var eps_a_basket_2 = 1;   // Basket shock variance
end;

// ============================================================================
// SOLUTION AND SIMULATION
// ============================================================================

steady;  // Compute steady state
check;   // Check Blanchard-Kahn conditions

// First-order approximation with 20-period IRFs
stoch_simul(order=1, irf=20, graph_format=pdf);
